# Generated by Django 3.1.5 on 2024-04-17 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20240410_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='master_password',
        ),
        migrations.AddField(
            model_name='site',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
