# Generated by Django 3.1.5 on 2024-04-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240417_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='website_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
