# Generated by Django 3.1.5 on 2024-04-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240424_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['created']},
        ),
    ]
